### PR TITLE
Add build workflow for Linux

### PR DESCRIPTION
**Pull request by fire**
These changes enable automated builds for multiple platforms.

- [x] Looking for review and how to resolve the mac build error.
- [x] Upload the proper build rather than the entire build folder
- [x] Only build for Linux
- [x] Can submit only [windows, linux] for now
- [x] Build for windows from linux

### CODE REVIEW

**Comment by fire** [comment]
See the actions on https://github.com/fire/CoACD

image

**Comment by eliphatfs** [comment]
Thanks for the work on setting up CI for CoACD!
May be we should also include building pip wheels in the actions? What do you think about that?

**Comment by fire** [comment]
I agree, but I am wanting to do it in a secondary pr.

**Comment by fire** [comment]
Doing windows c++ executable and macos executable caused me to be stuck for most of today so don't think they're easy to do, but I wanted some progress.

**Pull request merged**
